[sdl]
autolock=false
waitonerror=false
[dosbox]
machine=svga_s3
memsize=16
quit warning=false
working directory option=noprompt
working directory default=/Users/kitrinx/workspace/Ultima8/projects/U8/out/dos
[cpu]
core=normal
cputype=386
cycles=max
[dos]
ems=false
[autoexec]
mount c "/Users/kitrinx/workspace/Ultima8/projects/U8/out/tools"
mount d "/Users/kitrinx/workspace/Ultima8/projects/U8/out/dos"
path=c:\bc\bin
date 01/01/1993
time 00:00:00
d:
call run.bat
exit
